### ISSUE TITLE
Make releases for usability

### ISSUE THREAD

**Issue by qk7b** [wernight/docker-alpine-nginx-pagespeed#1]
Thanks for this project.

Making releases is an easy way to provide usable images.
This way in production env, we can keep a fixed version and test new ones in local or staging

**Comment by wernight** [comment]
I probably would if upgrade were not so hard. They are really hard at the moment. I can tag the current version if you like. One issue with versioning is also which version to select: Nginx or PageSpeed? It's kind of both actually.

**Comment by qk7b** [comment]
That would be a great start! Thanks.

EDIT: For the versioning issue, why would you use another project's one ?

**Comment by wernight** [comment]
Added tagged version.
